// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfHhAz2KUmgdXlSRDUBoz1XBo9AWHahs',
    appId: '1:769983539710:web:4c3d7ca104e51e13a338af',
    messagingSenderId: '769983539710',
    projectId: 'gp2-5f66d',
    authDomain: 'gp2-5f66d.firebaseapp.com',
    storageBucket: 'gp2-5f66d.appspot.com',
    measurementId: 'G-2BJDDT2GSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7G9rziez5F5iEBNUdY3ByRH8W_6W4ko',
    appId: '1:769983539710:android:acbd281041a6a330a338af',
    messagingSenderId: '769983539710',
    projectId: 'gp2-5f66d',
    storageBucket: 'gp2-5f66d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwOEknsUeJOe8Qn_2JcOQ8c-lfOeOJdeM',
    appId: '1:769983539710:ios:02356c9079386afca338af',
    messagingSenderId: '769983539710',
    projectId: 'gp2-5f66d',
    storageBucket: 'gp2-5f66d.appspot.com',
    androidClientId: '769983539710-lko4j722d93vc7fs77f2opl8be1ag67o.apps.googleusercontent.com',
    iosClientId: '769983539710-nniojo482gnvlhjhibm8539gl296sr77.apps.googleusercontent.com',
    iosBundleId: 'com.example.libManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwOEknsUeJOe8Qn_2JcOQ8c-lfOeOJdeM',
    appId: '1:769983539710:ios:02356c9079386afca338af',
    messagingSenderId: '769983539710',
    projectId: 'gp2-5f66d',
    storageBucket: 'gp2-5f66d.appspot.com',
    androidClientId: '769983539710-lko4j722d93vc7fs77f2opl8be1ag67o.apps.googleusercontent.com',
    iosClientId: '769983539710-nniojo482gnvlhjhibm8539gl296sr77.apps.googleusercontent.com',
    iosBundleId: 'com.example.libManagement',
  );
}
